### A CI workflow template that runs linting and python testing
### TODO: Modify as needed or as desired.

name: Test target-starrocks

on:
  push:
    branches: [main]
    paths:
    - .github/workflows/test.yml
    - target_starrocks/**
    - tests/**
    - docker-compose.yml
    - poetry.lock
    - pyproject.toml
    - tox.ini
  pull_request:
    branches: [main]
    paths:
    - .github/workflows/test.yml
    - target_starrocks/**
    - tests/**
    - docker-compose.yml
    - poetry.lock
    - pyproject.toml
    - tox.ini
  workflow_dispatch:

env:
  FORCE_COLOR: 1
  # renovate: datasource=pypi depName=tox
  TOX_VERSION: 4.24.1
  # renovate: datasource=pypi depName=tox-uv
  TOX_UV_VERSION: 1.20.1
  # renovate: datasource=pypi depName=uv
  UV_VERSION: 0.5.24

jobs:
  pytest:
    runs-on: ubuntu-latest
    env:
      STARROCKS_DATABASE: pytest
      STARROCKS_PORT: 9030

    strategy:
      fail-fast: false
      matrix:
        python-version:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - run: |
        docker compose up --quiet-pull --wait
        docker compose exec starrocks mysql -P ${{ env.STARROCKS_PORT }} -h 127.0.0.1 -u root -e 'create database if not exists ${{ env.STARROCKS_DATABASE }}'
        docker compose ps
    - uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - uses: astral-sh/setup-uv@887a942a15af3a7626099df99e897a18d9e5ab3a # v5.1.0
      with:
        version: ${{ env.UV_VERSION }}
    - name: Run Tox
      env:
        TARGET_STARROCKS_USER: root
        TARGET_STARROCKS_HOST: localhost
        TARGET_STARROCKS_PORT: ${{ env.STARROCKS_PORT }}
        TARGET_STARROCKS_DATABASE: ${{ env.STARROCKS_DATABASE }}
      run: >
        uvx
        --with tox-uv==${{ env.TOX_UV_VERSION }}
        --with tox==${{ env.TOX_VERSION }}
        tox -e $(echo py${{ matrix.python-version }} | tr -d .)
